### ISSUE TITLE
No animations

### ISSUE THREAD

**Issue by 0-Vanes-0** [Etherpod/ExpeditionTakeoff#1]
After pressing "Resume expedition" the planet just goes black.

OWML and Expedition Takeoff are up to date.

There's only one error message from OWML in logs:
```NullReferenceException: Object reference not set to an instance of an object
Stacktrace: TabbedNavigation.Awake () (at <bb45013cdd174c6e9670b07181b0b751>:0)
UnityEngine.Object:Instantiate(Button)
OWML.ModHelper.Menus.NewMenuSystem.OptionsMenuManager:CreateButton(Menu, String, String, MenuSide)
OWML.ModHelper.Menus.NewMenuSystem.MenuManager:SetupMenus(IList`1)
OWML.ModHelper.Menus.NewMenuSystem.MenuManager:<.ctor>b__27_1(OWScene, OWScene)
LoadManager:OnSceneLoaded(Scene, LoadSceneMode)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

**Comment by Etherpod** [comment]
How quickly does your game load? The animation should begin a couple seconds after the campfire goes out.

I’m pretty sure that error is a normal error from opening the settings menu.

**Comment by 0-Vanes-0** [comment]
A couple of seconds, no matter what value is set in settings. Also no other mods were installed.

**Comment by Etherpod** [comment]
Does this log show up at all?
![image](https://github.com/user-attachments/assets/5278231d-2f8c-43c4-bbb8-40f2c7d2d011)
And what platform are you on? I can't reproduce the bug or error message on Windows

**Comment by 0-Vanes-0** [comment]
Yes, I have this message. I'm playing on Windows. I guess, it's better to provide a footage of the bug:


https://github.com/user-attachments/assets/cb74ccbe-89e1-4392-93de-566fb6d681ba

**Comment by Etherpod** [comment]
The video really helps, thanks.

It looks like it's just loading too quickly for the animation to play. Did you already try turning on the option to extend the loading time in the mod settings?
(you need to click the checkbox to actually enable it, the slider won't change anything if it's off)

**Comment by 0-Vanes-0** [comment]
Okay, it works. It's weird that this option isn't checked by default. My game is installed on SSD.

(Also is this normal that sometimes the ship crashes to pines? ::D )

**Comment by Etherpod** [comment]
The option is disabled by default so that computers that take a bit to load the game don't take even longer. I can't really predict how quickly your computer will load it.
I can see how the two options might be confusing, so in the next update I'll compress it into just a slider and have the very left be 0 delay.
The ship crashing is intentional, I didn't make the animations procedural or anything XD
